"""Create tribute tables

Revision ID: 2fa2fa03b0ef
Revises:
Create Date: 2025-11-09 14:38:02.186869

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2fa2fa03b0ef"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tributes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("extra_fields", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tribute_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tribute_id", sa.Integer(), nullable=False),
        sa.Column("photo_b64", sa.Text(), nullable=False),
        sa.Column("photo_content_type", sa.String(length=64), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("caption", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["tribute_id"], ["tributes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tribute_photos")
    op.drop_table("tributes")
    # ### end Alembic commands ###
